"""
Run routes — Execute Gex runs (single file, full repo) with WebSocket streaming.
"""
from fastapi import APIRouter, HTTPException, WebSocket, WebSocketDisconnect
from pydantic import BaseModel
from typing import Optional
import json
import asyncio

from gex.runner import GexRunner
from gex.types import GexConfig

router = APIRouter(prefix="/api/run", tags=["run"])

# Runner instance — reconfigured when settings change
_runner: Optional[GexRunner] = None


def get_runner() -> GexRunner:
    global _runner
    if _runner is None:
        _runner = GexRunner(GexConfig())
    return _runner


def reconfigure_runner(config: GexConfig):
    global _runner
    _runner = GexRunner(config)


class RunFileRequest(BaseModel):
    repo_path: str
    file_path: str
    focus: Optional[str] = None


class RunRepoRequest(BaseModel):
    repo_path: str
    focus: Optional[str] = None
    mode: str = "sequential"


@router.post("/file")
async def run_file(req: RunFileRequest):
    """Run Gex on a single file. Returns full result with diff."""
    runner = get_runner()

    if not runner.config.api_key:
        raise HTTPException(
            status_code=400,
            detail="API key not configured. Set it in Settings.",
        )

    result = await runner.run_file(req.repo_path, req.file_path, focus=req.focus)
    return result.model_dump()


@router.post("/repo")
async def run_repo(req: RunRepoRequest):
    """Start a full repo Gex run. Returns run_id for tracking."""
    runner = get_runner()

    if not runner.config.api_key:
        raise HTTPException(
            status_code=400,
            detail="API key not configured. Set it in Settings.",
        )

    # Create the run and return the ID immediately
    import uuid
    run_id = str(uuid.uuid4())[:8]

    # Start the run in background
    asyncio.create_task(_run_repo_background(runner, run_id, req))

    return {"run_id": run_id, "status": "started"}


async def _run_repo_background(runner: GexRunner, run_id: str, req: RunRepoRequest):
    """Background task that processes the repo run."""
    async for run_state, file_result in runner.run_repo(
        req.repo_path, focus=req.focus, mode=req.mode, run_id=run_id
    ):
        # Results are stored in the runner's run state
        pass


@router.get("/{run_id}/status")
async def get_run_status(run_id: str):
    """Get the current status of a run."""
    runner = get_runner()
    state = runner.get_run_state(run_id)
    if state is None:
        raise HTTPException(status_code=404, detail=f"Run not found: {run_id}")
    return state.model_dump()


@router.get("/{run_id}/diffs")
async def get_run_diffs(run_id: str):
    """Get all diffs generated by a run."""
    runner = get_runner()
    state = runner.get_run_state(run_id)
    if state is None:
        raise HTTPException(status_code=404, detail=f"Run not found: {run_id}")

    diffs = []
    for result in state.results:
        if result.diff:
            diffs.append(result.diff.model_dump())

    return {"run_id": run_id, "diffs": diffs}


@router.websocket("/ws/{run_id}/stream")
async def ws_run_stream(websocket: WebSocket, run_id: str):
    """
    WebSocket endpoint for real-time run streaming.
    Sends per-file updates as they happen.
    """
    await websocket.accept()
    runner = get_runner()

    try:
        # Check if this is a new run request
        state = runner.get_run_state(run_id)

        if state and state.state == "completed":
            # Send all existing results
            for result in state.results:
                await websocket.send_json({
                    "type": "file_update",
                    "file": result.file,
                    "status": result.status,
                    "progress": 1.0,
                    "diff": result.diff.model_dump() if result.diff else None,
                })
            await websocket.send_json({"type": "run_complete", "run_id": run_id})

        elif state and state.state == "running":
            # Poll for updates
            last_processed = 0
            last_tool_step = None
            while True:
                current_state = runner.get_run_state(run_id)
                if current_state is None:
                    break

                # Stream tool call progress whenever current_file changes
                if current_state.current_file and current_state.current_file != last_tool_step:
                    last_tool_step = current_state.current_file
                    await websocket.send_json({
                        "type": "tool_step",
                        "message": current_state.current_file,
                    })

                # Send any new file results
                for i in range(last_processed, len(current_state.results)):
                    result = current_state.results[i]
                    await websocket.send_json({
                        "type": "file_update",
                        "file": result.file,
                        "status": result.status,
                        "progress": current_state.progress,
                        "diff": result.diff.model_dump() if result.diff else None,
                    })

                last_processed = len(current_state.results)

                if current_state.state in ("completed", "failed"):
                    await websocket.send_json({
                        "type": "run_complete",
                        "run_id": run_id,
                        "state": current_state.state,
                    })
                    break

                await asyncio.sleep(0.3)


    except WebSocketDisconnect:
        pass
    except Exception as e:
        try:
            await websocket.send_json({"type": "error", "message": str(e)})
        except Exception:
            pass


class ApplyPatchesRequest(BaseModel):
    file_path: str
    accepted_hunks: list[int]  # Indices of hunks to apply
    hunks: list[dict]  # The actual hunk data


@router.post("/apply")
async def apply_patches(req: ApplyPatchesRequest):
    """Apply only the accepted hunks to the original file."""
    from pathlib import Path

    file_path = Path(req.file_path)
    if not file_path.exists():
        raise HTTPException(status_code=404, detail=f"File not found: {req.file_path}")

    try:
        original = file_path.read_text(encoding="utf-8", errors="replace")
        lines = original.split("\n")

        # Build list of hunks to apply from accepted indices
        accepted = []
        for idx in req.accepted_hunks:
            if idx < len(req.hunks):
                accepted.append(req.hunks[idx])

        # Apply bottom-up so earlier line numbers stay valid after each splice
        accepted.sort(key=lambda h: h.get("start", 1), reverse=True)

        for hunk in accepted:
            # start is 1-indexed inclusive; convert to 0-indexed
            start_0 = hunk.get("start", 1) - 1
            before_lines = hunk.get("before_lines", [])
            after_lines  = hunk.get("after_lines",  [])

            # The slice to remove is exactly start_0 .. start_0 + len(before_lines)
            # This is always correct regardless of the "end" field.
            end_0 = start_0 + len(before_lines)
            lines[start_0:end_0] = after_lines

        new_content = "\n".join(lines)
        file_path.write_text(new_content, encoding="utf-8")

        return {
            "status": "applied",
            "file": str(file_path),
            "hunks_applied": len(accepted),
            "new_content": new_content,
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to apply patches: {str(e)}")

