/**
 * test-app — Electron Main Process
 * Generated by Gene 🧬
 */

const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');
const { spawn } = require('child_process');

const isDev = process.env.GENE_DEV === 'true' || !app.isPackaged;
const PYTHON_PORT = 18764;
const WS_PORT = 18765;

let mainWindow = null;
let pythonProcess = null;

// ─── Python Lifecycle ───────────────────────────────────────────
function startPython() {
  const pythonPath = isDev
    ? 'python'
    : path.join(process.resourcesPath, 'python', process.platform === 'win32' ? 'app.exe' : 'app');

  const args = isDev
    ? ['-m', 'uvicorn', 'app:app', '--host', '127.0.0.1', '--port', String(PYTHON_PORT), '--reload']
    : ['--port', String(PYTHON_PORT)];

  const cwd = isDev ? path.join(__dirname, '..', 'backend') : undefined;

  console.log(`🐍 Starting Python: ${pythonPath} ${args.join(' ')}`);

  pythonProcess = spawn(pythonPath, args, {
    cwd,
    stdio: ['pipe', 'pipe', 'pipe'],
    env: { ...process.env, GENE_PORT: String(PYTHON_PORT), GENE_WS_PORT: String(WS_PORT) },
  });

  pythonProcess.stdout.on('data', (data) => {
    console.log(`[Python] ${data.toString().trim()}`);
  });

  pythonProcess.stderr.on('data', (data) => {
    console.error(`[Python] ${data.toString().trim()}`);
  });

  pythonProcess.on('close', (code) => {
    console.log(`🐍 Python exited with code ${code}`);
    if (code !== 0 && code !== null) {
      setTimeout(() => startPython(), 2000);
    }
  });
}

function stopPython() {
  if (pythonProcess) {
    console.log('🐍 Stopping Python...');
    pythonProcess.kill('SIGTERM');
    setTimeout(() => {
      if (pythonProcess && !pythonProcess.killed) {
        pythonProcess.kill('SIGKILL');
      }
    }, 3000);
    pythonProcess = null;
  }
}

// ─── Health Check ───────────────────────────────────────────────
async function waitForPython(maxRetries = 30) {
  const http = require('http');
  
  for (let i = 0; i < maxRetries; i++) {
    try {
      await new Promise((resolve, reject) => {
        const req = http.get(`http://127.0.0.1:${PYTHON_PORT}/health`, (res) => {
          if (res.statusCode === 200) resolve();
          else reject(new Error(`Status ${res.statusCode}`));
        });
        req.on('error', reject);
        req.setTimeout(1000, () => { req.destroy(); reject(new Error('timeout')); });
      });
      console.log('✅ Python backend is ready');
      return true;
    } catch {
      await new Promise(r => setTimeout(r, 500));
    }
  }
  console.error('❌ Python backend failed to start');
  return false;
}

// ─── Window ─────────────────────────────────────────────────────
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 800,
    minHeight: 600,
    title: 'test-app',
    backgroundColor: '#0f0f14',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
    titleBarStyle: 'hiddenInset',
    show: false,
  });

  if (isDev) {
    mainWindow.loadURL('http://localhost:3000');
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  } else {
    mainWindow.loadFile(path.join(__dirname, '..', 'frontend', 'dist', 'index.html'));
  }

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ─── IPC ────────────────────────────────────────────────────────
ipcMain.handle('app:get-config', () => ({
  pythonPort: PYTHON_PORT,
  wsPort: WS_PORT,
  isDev,
  platform: process.platform,
}));

ipcMain.handle('app:restart-python', async () => {
  stopPython();
  startPython();
  return await waitForPython();
});

// ─── App Lifecycle ──────────────────────────────────────────────
app.whenReady().then(async () => {
  startPython();
  await waitForPython();
  createWindow();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('will-quit', () => {
  stopPython();
});
