import { useState, useEffect } from 'react';

export default function TosModal() {
  const [showTos, setShowTos] = useState(false);
  const [scrolledToBottom, setScrolledToBottom] = useState(false);

  useEffect(() => {
    // Check local storage to see if TOS was already accepted
    const accepted = localStorage.getItem('gex_tos_accepted');
    if (!accepted) {
      setShowTos(true);
    }
  }, []);

  const handleScroll = (e) => {
    const bottom = e.target.scrollHeight - e.target.scrollTop <= e.target.clientHeight + 20;
    if (bottom) {
      setScrolledToBottom(true);
    }
  };

  const handleAccept = () => {
    localStorage.setItem('gex_tos_accepted', 'true');
    setShowTos(false);
  };

  if (!showTos) return null;

  return (
    <div className="settings-overlay" style={{ zIndex: 9999, backdropFilter: 'blur(8px)' }}>
      <div className="settings-card glass" style={{ maxWidth: '600px', width: '90%', maxHeight: '80vh', display: 'flex', flexDirection: 'column' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
          <img src="/gex-gecko.png" alt="AiAssist" style={{ width: '32px', height: '32px', borderRadius: '6px', border: '1px solid var(--signal-cyan)' }} />
          <div>
            <h2 style={{ margin: 0 }}>_Gex Terms of Service</h2>
            <p className="subtitle" style={{ margin: 0, color: 'var(--copper)' }}>Please read and accept to continue</p>
          </div>
        </div>

        <div 
          className="tos-content" 
          onScroll={handleScroll}
          style={{ 
            flex: 1, 
            overflowY: 'auto', 
            padding: '16px', 
            background: 'rgba(4, 8, 16, 0.6)', 
            border: '1px solid var(--panel-border)', 
            borderRadius: 'var(--radius-md)',
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: '0.75rem',
            lineHeight: 1.6,
            color: 'var(--text-secondary)',
            marginBottom: '20px'
          }}
        >
          <h3 style={{ color: 'var(--text-primary)', marginBottom: '8px' }}>1. Acceptance of Terms</h3>
          <p style={{ marginBottom: '16px' }}>
            By accessing and using _Gex, powered by AiAssist.net, you accept and agree to be bound by the terms and provision of this agreement.
          </p>

          <h3 style={{ color: 'var(--text-primary)', marginBottom: '8px' }}>2. Experimental AI modifications</h3>
          <p style={{ marginBottom: '16px' }}>
            _Gex is an AI-native code surgery environment. The patches, file modifications, and diagnostic outputs are generated by artificial intelligence. 
            You acknowledge that AI-generated code is inherently experimental. It may contain bugs, compile errors, logic flaws, or security vulnerabilities. 
            <strong>You are solely responsible for reviewing all diffs before applying them.</strong>
          </p>

          <h3 style={{ color: 'var(--text-primary)', marginBottom: '8px' }}>3. Limitation of Liability</h3>
          <p style={{ marginBottom: '16px' }}>
            In no event shall AiAssist.net, its developers, or affiliates be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use of _Gex. 
            This includes, without limitation, production downtime, server crashes, data loss, code corruption, or security breaches resulting from the application of AI-generated patches. 
          </p>

          <h3 style={{ color: 'var(--text-primary)', marginBottom: '8px' }}>4. Data Privacy & Transmission</h3>
          <p style={{ marginBottom: '16px' }}>
            To generate code modifications, excerpts of your provided repository are securely transmitted to the configured AI API providers via your backend server. 
            You agree not to utilize _Gex with repositories containing unencrypted personally identifiable information (PII) or plaintext production secrets.
          </p>

          <h3 style={{ color: 'var(--text-primary)', marginBottom: '8px' }}>5. Local Cloning & Execution</h3>
          <p style={{ marginBottom: '16px' }}>
            When you provide a remote Git repository URL, your code is downloaded as a ZIP archive and extracted locally within the _Gex sandbox environment strictly for static analysis and text-based structural diffing. 
            <strong>Your code is never compiled, executed, or otherwise run during runtime on our servers.</strong>
          </p>

          <h3 style={{ color: 'var(--text-primary)', marginBottom: '8px' }}>6. "AS IS" Warranty</h3>
          <p>
            The software is provided "AS-IS", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, and non-infringement.
          </p>
        </div>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
            {!scrolledToBottom ? "Scroll to the bottom to accept" : "Thank you for reading."}
          </span>
          <button 
            className="btn btn-copper" 
            onClick={handleAccept} 
            disabled={!scrolledToBottom}
            style={!scrolledToBottom ? { opacity: 0.5, cursor: 'not-allowed' } : {}}
          >
            I Accept and Understand
          </button>
        </div>
      </div>
    </div>
  );
}
