"""
test-app — Python Backend
FastAPI application serving as the intelligence layer.
Generated by Jenny 🧬
"""

import asyncio
import logging
from contextlib import asynccontextmanager

import uvicorn
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware

from routes import router as api_router

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("test_app")


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("🚀 test-app backend starting...")
    yield
    logger.info("👋 test-app backend shutting down...")


app = FastAPI(
    title="test-app API",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routes
app.include_router(api_router, prefix="/api")


@app.get("/health")
async def health():
    return {"status": "healthy", "app": "test-app"}


# ─── WebSocket ───────────────────────────────────────────────────
connections: dict = {}


@app.websocket("/ws")
async def websocket_endpoint(ws: WebSocket):
    await ws.accept()
    client_id = id(ws)
    connections[client_id] = ws
    logger.info(f"WebSocket client connected: {client_id}")

    try:
        await ws.send_json({"type": "connected", "payload": {"clientId": str(client_id)}})
        while True:
            data = await ws.receive_json()
            msg_type = data.get("type", "")

            if msg_type == "ping":
                await ws.send_json({"type": "pong"})
            else:
                # Echo back for demo — replace with your own handlers
                await ws.send_json({
                    "type": f"{msg_type}:response",
                    "payload": {"received": data.get("payload", {})},
                })
    except WebSocketDisconnect:
        connections.pop(client_id, None)
        logger.info(f"WebSocket client disconnected: {client_id}")


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=18764)
